Fix version extraction from release tag (#861)
* Fix version extraction from release tag

* Fix version extraction and formatting in Release.yml

diff --git a/.github/workflows/Release.yml b/.github/workflows/Release.yml
--- a/.github/workflows/Release.yml
+++ b/.github/workflows/Release.yml
@@ -9,14 +9,20 @@ jobs:
     name: Get Release Version
     runs-on: ubuntu-latest
     outputs:
-        version: ${{ steps.get_version.outputs.version }}
+      version: ${{ steps.get_version.outputs.version }}
 
     steps:
       - name: Determine version from release tag
         id: get_version
         run: |
-          release_tag=${{github.ref}}
-          version="${release_tag#refs/tags/v}"
+          release_tag="${{ github.event.release.tag_name }}"
+          version="${release_tag#v}"
+
+          if [[ -z "$version" ]]; then
+            echo "::error::Derived version is empty."
+            exit 1
+          fi
+
           echo "version=$version" >> "$GITHUB_OUTPUT"
 
   build:
@@ -24,14 +30,14 @@ jobs:
     needs: version
     uses: ./.github/workflows/Build.yml
     with:
-      version: ${{needs.version.outputs.version}}
+      version: ${{ needs.version.outputs.version }}
 
   test:
     name: Test
     needs: build
     uses: ./.github/workflows/Test.yml
     secrets: inherit
-  
+
   publish:
     name: Publish
     needs: [ version, test ]
@@ -42,4 +48,4 @@ jobs:
       contents: read
       packages: write
     with:
-      version: ${{needs.version.outputs.version}}
+      version: ${{ needs.version.outputs.version }}
